name: "Workshop Registration — GIT Going with GitHub"
description: "Register for the GIT Going with GitHub workshop (March 6–7, 2026)"
title: "[REGISTER] GIT Going with GitHub — March 2026"
labels: ["registration"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome! You are registering for GIT Going with GitHub.

        **Dates:** Friday, March 6 and Saturday, March 7, 2026
        **Time:** 12:00 PM — 8:00 PM Eastern (both days)
        **Cost:** Free
        **Capacity:** 75 participants

        Filling out this form is your first GitHub interaction — and it counts. You are already learning. All fields below are accessible with NVDA, JAWS, and VoiceOver.

  - type: input
    id: first-name
    attributes:
      label: First Name
      description: Your first name as you would like to be addressed during the workshop.
      placeholder: Jane
    validations:
      required: true

  - type: input
    id: last-name
    attributes:
      label: Last Name
      description: Your last name.
      placeholder: Doe
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email Address
      description: We will use this to send you Zoom links and workshop materials before the event.
      placeholder: jane.doe@example.com
    validations:
      required: true

  - type: input
    id: github-username
    attributes:
      label: GitHub Username
      description: "Your GitHub username (the one that appears in your profile URL: github.com/your-username). If you have not created a GitHub account yet, visit github.com/signup first."
      placeholder: janedoe
    validations:
      required: true

  - type: dropdown
    id: proficiency
    attributes:
      label: GitHub Proficiency Level
      description: How would you describe your current experience with GitHub? There is no wrong answer — this helps us prepare the right level of support for you.
      options:
        - "Brand new — I have never used GitHub before"
        - "Beginner — I have a GitHub account but have not done much with it"
        - "Intermediate — I have created repositories, filed issues, or opened pull requests"
        - "Experienced — I use GitHub regularly for projects or work"
    validations:
      required: true

  - type: dropdown
    id: screen-reader
    attributes:
      label: Primary Screen Reader
      description: Which screen reader do you primarily use? This helps us prepare targeted guidance.
      options:
        - "NVDA (Windows)"
        - "JAWS (Windows)"
        - "VoiceOver (macOS)"
        - "VoiceOver (iOS)"
        - "Other or none"
    validations:
      required: false

  - type: textarea
    id: questions
    attributes:
      label: Questions or Accommodations
      description: Any questions about the workshop, or accommodations we should arrange? Leave blank if none.
      placeholder: |
        I need a sign language interpreter.
        Can I attend only Day 1?
        I use a refreshable braille display — will that work?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **What happens next:** After you submit, you will see a confirmation comment on your issue. We will email your Zoom link before the workshop. If you have questions, email [support@bits-acb.org](mailto:support@bits-acb.org).

        Welcome aboard. You belong here.
